### ISSUE TITLE
Error when using a non-human host bmtagger index

### ISSUE THREAD

**Issue by Jimaz** [bxlab/metaWRAP#127]
Greetings, I have problems when using the "-x" opt while executing the read_qc module. If you specify a different host from hg38, it reports the file doesn't exists, which is correct, but it has to take the prefix you pass the argument.
I think the error is in line 92 in the read_qc.sh script, because if I comment those lines it works fine. 

`if [ ! -s ${BMTAGGER_DB}/hg38.bitmask ] && [ "$bmtagger" = "true" ]; then
	error "${BMTAGGER_DB}/hg38.bitmask file doesnt exist. Please configure your bmtagger human genome index"
fi`

Thanks!

**Comment by ursky** [comment]
Thank you for reporting this. I fixed the problem and it should be reflected in `metawrap v1.1.4`, when it comes out, or you can copy the script from this github repository.
