### ISSUE TITLE
Quant font size too large for 406 bin numbers to display on heatmap

### ISSUE THREAD

**Issue by TJrogers86** [bxlab/metaWRAP#171]

**Comment by TJrogers86** [comment]
I was wondering if there is any way to adjust the font size in the code for the Quant module? I have 406 bins. The heat map worked wonderfully, except that the font size for the bin numbers is causing so much overlap that one can not read the bin number

**Comment by ursky** [comment]
If you know some python, you can edit the existing plotting script and re-make the heatmap. The heatmap is made with the Seaborn clustermap package. I dont know the commands by heart but do recall there being a way to change fonts - google around for it. 

However, my real recommendation would be to take the output table and make the heatmap yourself with the software you are most comfortable with.

**Comment by TJrogers86** [comment]
Great advice. Thanks for the quick response.
