### ISSUE TITLE
Final step in "Classify_bins" module

### ISSUE THREAD

**Issue by Jimaz** [bxlab/metaWRAP#178]
Hello @ursky,

this script doesn't execute the final step. I think it's because of the _if_ statement returning false (line 170):

```
if false; then
comm "renaming bins to their best taxonomy"
mkdir ${out}/renamed_bins
for bin in $(ls $bin_folder); do 
	tax=$(cat ${out}/bin_taxonomy.tab | awk -v bin=$bin '$1==bin' | cut -f2)
	best_tax=$(echo $tax | rev | cut -d';' -f1 | rev | cut -d'_' -f1)
	no_spaces=${best_tax// /_}
	final_name=${no_spaces//./}
	echo "$bin was renamed to ${final_name}.fa"
	cp ${bin_folder}/$bin ${out}/renamed_bins/${final_name}.fa
done

comm "cleaning up..."
mkdir ${out}/work_files
for file in $(ls $out | grep -v "contig_taxonomy.tab" | grep -v "bin_taxonomy.tab"); do
	mv ${out}/$file ${out}/work_files/
done

comm "you will find the bins taxonomy estimates in ${out}/bin_taxonomy.tab"
fi
```
And related to this, I managed to draw a newick tree with taxknife. Do you think would it be a good idea to include this in the module? 
Sort of 
` cat ./binned_predictions.txt | taxknife -f 2 --mode tree -q species genus family phylum -v > ./tree2.newick
`

Thank's!

**Comment by ursky** [comment]
That section of the code is intentionally depricated because it does not always work for all classifications, and doesn't work at all on unclassified bins. Its simpler if the user renames the bins how they see fit. As for the tree, that would be cool, but your proposed code gives a tree of the contigs, not the bins.

**Comment by Jimaz** [comment]
Oh, I see. This is my first experience with metagenomics and I'm still a bit lost. Thank you very much for the response. I'll try to find a way to extract a tree of the bins.
