### ISSUE TITLE
Something went wrong with aligning

### ISSUE THREAD

**Issue by li0604** [bxlab/metaWRAP#220]
if there is someone got an error such as the tiltle showing that something went wrong with aligning R1 and R2.
This  is the error
```
Something went wrong with aligning                                      *****
*****                    XXX._1.fastq and                    *****
*****          XXX._2.fastq reads to the assembly.           *****
*****                                                   Exiting                             
```
Thanks a lot.

**Comment by ursky** [comment]
Please provide more information about the error. The exact command you ran, the full std_out, and std_error, etc.

**Comment by li0604** [comment]
Firstly,I am very grateful for your reply and let me know how to showing the error that i have gotten.Secondly i am so sorry for my question and i have found some error during the pre-dealing process with the software named fastp and fstuniq.Then i am testting the reanalysised data with metawrap.
