### ISSUE TITLE
metawrap read_qc fails with idx_reader.cpp:82 error

### ISSUE THREAD

**Issue by openpaul** [bxlab/metaWRAP#222]
I am launching metawrap read_qc and get this error:

```
RUNNING align_short for [...] merged/bmtagger_tmp/bmtagger.1568366049.hx-noah-01-15.25773.short'
reading queries.....................................................................................................................done
ERROR:   idx_reader.cpp:82 [1] read error (failed to read 1 bytes) <srprism.cpp:850>
```

I tried this with version 1.1.1, 1.1.8 and 1.2.2 and get the same error everytime. All installed from conda (https://anaconda.org/ursky/metawrap-mg)

Someone have an idea?

**Comment by ursky** [comment]
Did you load in and index the human genome for bmtagger? See database installation instructions. Worst case you can just skip this by using the `--skip-bmtagger` tag.

**Comment by openpaul** [comment]
Ah, I think I ruined my index sometime in the past. It looks destroyed, that why you make files readonly. 
Ok, I think thats it. will close for now.

Thank you
