### ISSUE TITLE
getting error during BIN_REASSEMBLY

### ISSUE THREAD

**Issue by li0604** [bxlab/metaWRAP#226]
Dear all, i got an error of my metawrap when BIN_REASSEMBLY.
my scripts
![图片](https://user-images.githubusercontent.com/54136123/65444666-1bbcd700-de63-11e9-8eea-a576dde8acd4.png)

the error 
![图片](https://user-images.githubusercontent.com/54136123/65444749-4ad34880-de63-11e9-8a8f-ddd6ba93a2ff.png)

and the results
![图片](https://user-images.githubusercontent.com/54136123/65444783-5d4d8200-de63-11e9-8330-04127d4a1131.png)

How can I deal with this error?
but this metawrap I have used Sep.23rd and it works, i didn't change any thing of my work environment. 

Thanks a lot !

**Comment by ursky** [comment]
Can you provide the full stdout and stderr output of metawrap? I cant tell where it failed from what you gave here

**Comment by li0604** [comment]
I can provide the full error file and log file. 

[metawrap.e20168.txt](https://github.com/bxlab/metaWRAP/files/3644648/metawrap.e20168.txt)
[metawrap.o20168.txt](https://github.com/bxlab/metaWRAP/files/3644649/metawrap.o20168.txt)

**Comment by ursky** [comment]
Thanks for the details. I honestly dont know whats going on. Can you try to manually assembly some of the bins with SPAdes (using some of the code from `reassemble_bins.sh`)? Maybe you will be able to isolate the error that way.

**Comment by li0604** [comment]
Thanks a lot.Because of some commands i have input and then the conda was destoried  yesterday.I can't activated the metawrap-env.Now I try to install everything now.If the new install softwares tested could work,i will tell you.

**Comment by li0604** [comment]
hello! I am so sorry that the metawrap isn't work yet.I have reinstall the miniconda and metawrap,then continuing the BIN_REASSEMBLY,and the error and log file showed as following:
 
[metawrap.e23284.txt](https://github.com/bxlab/metaWRAP/files/3665455/metawrap.e23284.txt)
[metawrap.o23284.txt](https://github.com/bxlab/metaWRAP/files/3665456/metawrap.o23284.txt)

I can't deal with this error.Would you help me.Thank you very much.

**Comment by ursky** [comment]
It says what is wrong right there in the stdout - you need to set the CheckM database directory. Look at the metawrap database installation instructions for details.

**Comment by li0604** [comment]
Thanks a lot. It works now and  doesn't show the initial error of BIN_REASSEMBLY.
