### ISSUE TITLE
Question about reassembly reducing number of bins

### ISSUE THREAD

**Issue by franciscozorrilla** [bxlab/metaWRAP#230]
Hi Gherman,

It looks like after bin refinement I have 4435 bins (across all my samples) but after bin reassembly I am left with only 4233 bins, is this result to be expected/normal?

What is strange to me is that when I summarize the "original_bins.stats" files from the reassembly output I only find 4233 even though the number of bins of the refinement output is 4435.

Thanks,
FZ

**Comment by ursky** [comment]
I don't have an immediate explanation, but the labels of the bins (numbering) is not altered during the process so you can just hunt down your missing bins in the originals.

**Comment by franciscozorrilla** [comment]
Thanks for the hint, turns out some of my samples failed the reassembly step hence the lesser number of bins. Will try re-running.
