### ISSUE TITLE
Something went wrong with indexing the assembly. Exiting.

### ISSUE THREAD

**Issue by DOieGYuan** [bxlab/metaWRAP#231]
When I use quant_bins module to quant bins, I type:
metawrap quant_bins -b metawrap_70_10_bins/ -o test -a original_contigs.fa *.fastq
After a while, it comes out like this:
[2019-10-29 12:58:37.548] [jointLog] [info] Replaced 0 non-ATCG nucleotides
[2019-10-29 12:58:37.548] [jointLog] [info] Clipped poly-A tails from 207 transcripts
[2019-10-29 12:58:37.614] [jointLog] [info] Building rank-select dictionary and saving to disk
[2019-10-29 12:58:37.763] [jointLog] [info] done
Elapsed time: 0.148421s
[2019-10-29 12:58:37.763] [jointLog] [info] Writing sequence data to file . . . 
[2019-10-29 12:58:39.117] [jointLog] [info] done
Elapsed time: 1.35436s
[2019-10-29 12:58:39.123] [jointLog] [info] Building 64-bit suffix array (length of generalized text is 3,571,615,046)
[2019-10-29 12:58:44.037] [jointLog] [info] Building suffix array . . . 
/usr/bin/metawrap-modules/quant_bins.sh: line 128: 27747 Segmentation fault      (core dumped) salmon index -p $threads -t $assembly -i ${out}/assembly_index

************************************************************************************************************************
*****                           Something went wrong with indexing the assembly. Exiting.                          *****
************************************************************************************************************************

real	3m54.610s
user	4m55.768s
sys	0m9.118s

My salmon is v0.13.1
I don't know what happen and how to fix it. What should I do?

**Comment by DOieGYuan** [comment]
I have tried conda install blas=2.5=mkl, it continue working, but error messages show up continuously like this:

ERROR (1): trying to add same suffix CCCTGCCACCGCCGATGGCTGCACCGTATTC (len = 31) multiple times!
existing interval is [534203976, 534203977)
*C**C**C**T**G**C**C**A**C**C**G**C**C**G**A**T**G**G**C**T**G**C**A**C**C**G**T**A**T**T**C* (len = 31)
new interval is [1104786420, 1104786421)
*C**C**C**T**G**C**C**A**C**C**G**C**C**G**A**T**G**G**C**T**G**C**A**C**C**G**T**A**T**T**C*
processed 1,223,000,000 positions
ERROR (1): trying to add same suffix CCTCTCCAATGTCTCGATCCGCAAGATAAGC (len = 31) multiple times!
existing interval is [1072426913, 1072426914)
*C**C**T**C**T**C**C**A**A**T**G**T**C**T**C**G**A**T**C**C**G**C**A**A**G**A**T**A**A**G**C* (len = 31)
new interval is [1223313570, 1223313571)
*C**C**T**C**T**C**C**A**A**T**G**T**C**T**C**G**A**T**C**C**G**C**A**A**G**A**T**A**A**G**C*
processed 1,224,000,000 positions

Is this normal? How to fix it

**Comment by ursky** [comment]
Interesting. This is coming from salmon only. The first error might be an "out of memory" problem on your system. The second I do not recognize. Have you tried running salmon manually (on anything) to see if it works at all?

**Comment by DOieGYuan** [comment]
> Interesting. This is coming from salmon only. The first error might be an "out of memory" problem on your system. The second I do not recognize. Have you tried running salmon manually (on anything) to see if it works at all?

Thank you for your reply! It seems the first error can be solved by `conda install blas=2.5=mkl`

I have tried to run salmon individually but the same errors are still coming out

**Comment by DOieGYuan** [comment]
Fine, I have solved this error. This is due to the hardware incompatiblility. After I upgrade my BIOS, all works well.
