### ISSUE TITLE
Should I use bin completeness to correct the abundance of genomic bins estimated by quant_bins module

### ISSUE THREAD

**Issue by DOieGYuan** [bxlab/metaWRAP#233]
Hi! I tried quant_bins module to estimate the abundance of my genomic bins and I noticed that the abundance was indicated by copies per million reads. That is the reads in a bin per million reads is normalized by the size of that bin. I wonder whether the size of the bin is the real size (result of binning) or the theoretical size (divide by completeness)? If not, can I use completeness to correct the abundance data? Thank you!

**Comment by ursky** [comment]
The abundance values from the quant_bins module have nothing to do with the bin length. They are effectively "read coverage" or "depth" values, thus independent form genome size.

**Comment by DOieGYuan** [comment]
Ok!T

> The abundance values from the quant_bins module have nothing to do with the bin length. They are effectively "read coverage" or "depth" values, thus independent form genome size.

Thanks!
