### ISSUE TITLE
metaSPAdes assembly error -9

### ISSUE THREAD

**Issue by lroppolo** [bxlab/metaWRAP#234]
Hi there, 

Thanks for all of your help so far, I am finally moving along with using the program! As of now, I am running MetaSPAdes in the assembly module, and I am getting hung up in the assembly at what I believe is the spades-hammer step. I tried troubleshooting on my own and looking at the SPAdes documentation, and it was suggested that I try requesting more RAM (I asked for 210GB of a 256GB max node), but I'm still running into the same problem. Do you have any other suggestions for this issue that might clear it up? Here are the spades.log and params.txt for one of four assemblies I'm running. All four are getting the same error: 
== Error ==  system call for: "['/users/lroppolo/.conda/envs/metawrap-env/share/spades-3.13.0-0/bin/spades-hammer', '/users/lroppolo/metawrap_UEGP/ATE_ASSEMBLY/metaspades/corrected/configs/config.info']" finished abnormally, err code: -9
[spades.log](https://github.com/ablab/spades/files/3827289/spades.log)
[params.txt](https://github.com/ablab/spades/files/3827291/params.txt)

**Comment by ursky** [comment]
I would recommend to just use the megahit option then. The results are very comparable but the memory footprint is much smaller, and so is the run time.

**Comment by lroppolo** [comment]
Megahit worked flawlessly! Thank you for your help!
