### ISSUE TITLE
genome copies per million reads

### ISSUE THREAD

**Issue by TJrogers86** [bxlab/metaWRAP#252]
I have a question about the normalized abundance calculated in the Quant module. It says that it is calculated in a similar way to TPM. However, when you calculate TPM and you sum all the transcripts in a replicate (say all transcripts from Sample site 1) the total should come out to 1 million for all replicates. However, with this genome copies per million reads out put, if I sum all the bins in each replicate, i get a variety of different numbers for each replicate and none of them are close to a million. Why is this?

**Comment by ursky** [comment]
The simple answer is that not all contigs in a given sample are binned, or even assembled, which complicates this calculation. The total is largely meaningless and is a function of how good the assembly and binning process was in that sample.

**Comment by TJrogers86** [comment]
I have a question. I am considering correlations of my MAGs across multiple sites. I have some MAGs that have high GPM in some sites, and really low GPM in other sites. I was wondering if these really low values could be due to small amounts of read recruitment to evolutionarily conserved sequences and not actual recruitment to an organism? At the end of the day, I would if I would be justified in using the highest abundance (.03 GPM) of my lowest abundant MAG across all sites as an abundance cutoff to remove this possibility. So the abunance of any MAG at a site < .03 GPM will be changed to 0. Then I run my correlation analysis on these values.
