### ISSUE TITLE
Binning using single-end and paired-end reads

### ISSUE THREAD

**Issue by ohickl** [bxlab/metaWRAP#254]
Hi, is it possible to input paired-end and single-end reads with the binning module?
```
metawrap binning -o initial_binning \
                 -t 1 \
                 -m 4 \
                 -a ../m1.1-v1_data/mgmt.assembly.merged.fa \
                 --metabat2 \
                 --maxbin2 \
                 --concoct \
                 --single-end ../m1.1-v1_data/reads/../m1.1-v1_data/reads/*se*.fastq \
                 ../m1.1-v1_data/reads/*r1*.fastq ../m1.1-v1_data/reads/*r2*.fastq #paired-end reads
```
When I input it as above metawrap will probably take all reads as single ended so it wont work.

Also, will metawrap also support more than 3 binners as input at the same time in the future, as binning_refiner now supports it?

Best
Oskar

**Comment by ursky** [comment]
You cannot use single end AND paired reads in the same run. This comes into play very rarely so I did not code for this. I would recommend just using the forward reads from your paired samples to get around this. The paired reverse read information is not as critical for the binning.

As for more binners, the simplest work adound is to tun bin_refinement several times. For example, if you have sets A, B, C, D, and E, run A+B+C, D+E, and finally a run combinning the resulting sets.

**Comment by ohickl** [comment]
Ok, I will try that. Thanks for the swift reply!
