### ISSUE TITLE
BLAST Database error: Error: Not a valid version 4 database.

### ISSUE THREAD

**Issue by kyoreth** [bxlab/metaWRAP#259]
Blastn produces this error when trying to run the blobology on the example NCBI_nt data.

Running Blast+ 2.6.0, metawrap v.1.2.3

Linux Ubuntu 18.04

**Comment by kyoreth** [comment]
Fixed: Updated Blast to 2.9.0

**Comment by JJMaggie** [comment]
how to update Blast to 2.9.0 ?

Many thanks!

**Comment by kyoreth** [comment]
I think it should be this one:
conda install -c bioconda blast

While in your metawrap conda environment :) 

Probably a good idea to uninstall blast first..

**Comment by vrou1995** [comment]
Hi,

This doesn't work for me for some reason. Updating blast breaks the metwrap Conda env.

Any idea why that might be?

**Comment by kyoreth** [comment]
Not sure actually, I'm not especially good at conda environments..

**Comment by yangjintao0626** [comment]
I met the same problem. How did you solve it
