### ISSUE TITLE
BLAST Database error: Error: Not a valid version 4 database.

### ISSUE THREAD

**Issue by JJMaggie** [bxlab/metaWRAP#263]
when I run  metawrap blobology 

BLAST Database error: Error: Not a valid version 4 database.

I re-install   BLAST to  Nucleotide-Nucleotide BLAST 2.2.28+

it also remind 
BLAST Database error: Error: Not a valid version 4 database.

Any other suggestions?

Many thanks!

#259

**Comment by yangjintao0626** [comment]
I met the same problem. How did I solve it
