### ISSUE TITLE
quant_bins problems

### ISSUE THREAD

**Issue by TianleiQiu** [bxlab/metaWRAP#270]
Hi, 
Thanks for the amazing pipelines. When I run the script "quant_bins" to get the abundance of bins, I got the "Number of F and R reads must be the same!" problem. I am sure of that we have definitely 3 forward and 3 reverse reads (fastq).
How can I make it?

Here is the logs:

metawrap quant_bins -b ./binning/bin_refinement/binsA_50_10/ -t 10 -o ./binning/bin_quant_slurry/ -a /dell2/workdir/qiutianlei/JJJ_cleandata/slurry/C11_1.fastq /dell2/workdir/qiutianlei/JJJ
_cleandata/slurry/C11_2.fastq /dell2/workdir/qiutianlei/JJJ_cleandata/slurry/GY2_1.fastq /dell2/workdir/qiutianlei/JJJ_cleandata/slurry/GY2_2.fastq /dell2/workdir/qiutianlei/JJJ_cleandata/s
lurry/MYHZ3_1.fastq /dell2/workdir/qiutianlei/JJJ_cleandata/slurry/MYHZ3_2.fastq

------------------------------------------------------------------------------------------------------------------------
-----                                  2 forward and 3 reverse read files detected                                 -----
------------------------------------------------------------------------------------------------------------------------

************************************************************************************************************************
*****                                   Number of F and R reads must be the same!                                  *****
************************************************************************************************************************

real	0m0.513s
user	0m0.037s
sys	0m0.056s

**Comment by TianleiQiu** [comment]
Sorry, I forgot the assemble contigs!

**Comment by yshengzhi** [comment]
> Sorry, I forgot the assemble contigs!

Hi, 
I have a question about the quant_bins.

The assembly.fa file (in the option -a assembly.fa) is  assembly of  all fastaq samples ?
