### ISSUE TITLE
classify bins error - BLAST Database error: 

### ISSUE THREAD

**Issue by srikanthkris** [bxlab/metaWRAP#274]
Hi, when i try to run classify bin module

I get the following error
BLAST Database error: Error: Not a valid version 4 database.

i guess the error might due to version conflict between megablast software and blast database ?
This could be a conflict between blastn program and blast db (db is in version 5)

blastn program version is 2.2.28+

Can you please help.

**Comment by Niicii** [comment]
I'm having the same problem when trying to run metawrap blobology. My blast database is version 5 and the metawrap environment is up to date but still using Nucleotide-Nucleotide BLAST 2.2.28+. 

I hope that at some point metaWRAP will use a newer blast version (?) but to keep things running until then I downloaded the blast database version 4 (using the command below) and pointed metawrap to the v4 database using the config file.  

`wget "ftp://ftp.ncbi.nlm.nih.gov/blast/db/v4/nt_v4.*.tar.gz" && for a in nt_v4.*.tar.gz; do tar xzf $a; done`

**Comment by srikanthkris** [comment]
Hi @Niicii 
Thanks for the info.

**Comment by ursky** [comment]
Thanks for the info! For the purposes of metawrap there is no need to upgrade blast yet, however, ill include these instructions for downloading more recent databases.
