### ISSUE TITLE
Error in bin_refinement CheckM issue

### ISSUE THREAD

**Issue by yilmazbah** [bxlab/metaWRAP#294]
Hi everyone,
When I run the bin refinement I got this following error:
```
------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------

It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
Where should CheckM store it's data?
Please specify a location or type 'abort' to stop trying: 
Traceback (most recent call last):
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/bin/checkm", line 36, in <module>
    from checkm import main
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 25, in <module>
    from checkm.defaultValues import DefaultValues
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/defaultValues.py", line 26, in <module>
    class DefaultValues():
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/defaultValues.py", line 29, in DefaultValues
    __DBM = DBManager()
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/checkmData.py", line 114, in __init__
    if not self.setRoot():
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/checkmData.py", line 140, in setRoot
    path = self.confirmPath(path=path)
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/checkmData.py", line 162, in confirmPath
    path = raw_input("Where should CheckM store it's data?\n" \
EOFError: EOF when reading a line

************************************************************************************************************************
*****                             Something went wrong with running CheckM. Exiting...                             *****
************************************************************************************************************************


real	20m32.963s
user	18m44.212s
sys	1m34.926s
```

Any suggestion how to solve this CheckM issue?

Thank you so much.

Best wishes,
Bahti

**Comment by ursky** [comment]
Please follow the database installation guide to set up the CheckM database. Then make sure you can get the checkm help message with no errors before re-trying metawrap.

**Comment by yilmazbah** [comment]
Dear Gherman, 

Thank you so much for a quick reply.

I follow your suggestion and it started to run but then again I got an error. It didn't do refinement to all I suppose.  I have refined bins in folders binsBC, AC, AB and ABC and I have empty binsA.tmp. I am not sure why it gives the similar error sincee database was set and worked until that step. Basically below you can find the end of the run:

Thank you so much for your help. Looking forrward to hear your suggestion.

Best wishes,
Bahti

------------------------------------------------------------------------------------------------------------------------
-----                                      there are 96 refined bins in binsAB                                     -----
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
-----                                     there are 109 refined bins in binsBC                                     -----
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
-----                                      there are 98 refined bins in binsAC                                     -----
------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
-----                                     there are 84 refined bins in binsABC                                     -----
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
-----                                     Bin refinement finished successfully!                                    -----
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
-----                            fixing bin naming to .fa convention for consistancy...                            -----
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
-----                              making sure every refined bin set contains bins...                              -----
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
-----                     Removing bin set binsA.checkm because it yielded 0 refined bins ...                      -----
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
-----                       Removing bin set binsA.tmp because it yielded 0 refined bins ...                       -----
------------------------------------------------------------------------------------------------------------------------


########################################################################################################################
#####                                      RUNNING CHECKM ON ALL SETS OF BINS                                      #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------

It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
Where should CheckM store it's data?
Please specify a location or type 'abort' to stop trying: 
Traceback (most recent call last):
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/bin/checkm", line 36, in <module>
    from checkm import main
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 25, in <module>
    from checkm.defaultValues import DefaultValues
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/defaultValues.py", line 26, in <module>
    class DefaultValues():
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/defaultValues.py", line 29, in DefaultValues
    __DBM = DBManager()
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/checkmData.py", line 114, in __init__
    if not self.setRoot():
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/checkmData.py", line 140, in setRoot
    path = self.confirmPath(path=path)
  File "/home/ubelix/dbmr/terziev/anaconda2/envs/metawrap-env/lib/python2.7/site-packages/checkm/checkmData.py", line 162, in confirmPath
    path = raw_input("Where should CheckM store it's data?\n" \
EOFError: EOF when reading a line

************************************************************************************************************************
*****                             Something went wrong with running CheckM. Exiting...                             *****
************************************************************************************************************************


real	20m32.663s
user	18m40.702s
sys	1m35.106s

**Comment by ursky** [comment]
CheckM clearly does not have its database set. Download all the database files as per instructions and run `checkm data setRoot ~/somepath/your_checkm_db` to set it up.

**Comment by yilmazbah** [comment]
Cheers! Totally my stupidity. Somehow I didn't set it correctly. Thank you so much for your time. It is running now.
