### ISSUE TITLE
REASSEMBLING BINS with megahit

### ISSUE THREAD

**Issue by ayixon** [bxlab/metaWRAP#296]
Hoelo, I wonder if would be possible to set the REASSEMBLING BINS module with Megahit instead of spades?

**Comment by ursky** [comment]
Megahit does not support single-genome assembly, it is exclusively for metagenomes. SPAdes on the other hand, has a single-genome mode that is used for the reassembly.

**Comment by ayixon** [comment]
Thak you very much
