### ISSUE TITLE
About READ_QC module

### ISSUE THREAD

**Issue by Vikicai** [bxlab/metaWRAP#300]
Hello, I have a question about the READ_QC module. 
We got the sequences and adapter.fa from the company, but Metawrap did't require me to input the adapter.fa . 
May I ask whether it has been cut?
Or do I need to use some other software to cut the adaper myself?
Thanks！

**Comment by ursky** [comment]
Trimgalore (the trimming software inside read_qc) autodetects the adapters used in the sequences. Some other software allows you to manually specify the adapter sequences too. Up to you which you use, its unlikely to make a big difference.

**Comment by Vikicai** [comment]
Thanks for your reply!
