### ISSUE TITLE
metaspades err code: -9

### ISSUE THREAD

**Issue by valentinachz** [bxlab/metaWRAP#316]
Hello, I have a problem with metaspades. I am able to get the ASSEMBLY directory, but not the final_assembly.fasta and assembly_report.html files.

Thank you.

[params.txt](https://github.com/bxlab/metaWRAP/files/5442839/params.txt)
[spades.log](https://github.com/bxlab/metaWRAP/files/5442840/spades.log)

**Comment by ursky** [comment]
I would make an error report directly to the SPAdes team - I don't think this is a metawrap issue. That being said, any time i see strange errors with SPAdes I always suspect that it ran out of memory (it needs a lot). Try running on a small subset of your reads to see it that fixes it - then you will know.

**Comment by valentinachz** [comment]
Thank you for your help.
