### ISSUE TITLE
database_path and KRAKEN2

### ISSUE THREAD

**Issue by cbar123** [bxlab/metaWRAP#328]
Hi, 
I have two issues: 
1. After making an update of metawrap (v.1.3.2) I cannot assign my database paths to the config-metawrap file anymore. Do you maybe have any idea why?or what can I do?

2. I aim to use the kraken2 module but once I try to build the database I get following error: 
kraken2-build --standard --threads 24 --db MY_KRAKEN2_DATABASE
Downloading taxonomy tree data...rsync: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory.

Can you maybe help me with that?

Thank you in advance.

**Comment by ursky** [comment]
1. You will need to provide more details. 
2. Kraken is telling you what C++ library is missing on your system - install it and try again.

**Comment by cbar123** [comment]
Hi, 

2. Thanks. It seems to work now, however I get a new error: 

kraken2-build --standard --threads 24 --db MY_KRAKEN2_DB
 Downloading taxonomy tree data... done.
Untarring taxonomy tree data... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 387 projects (602 sequences, 1.01 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
rsync_from_ncbi.pl: unexpected FTP path (new server?) for na

Do you have any idea how to fix that?

Thanks a lot for your help.
