### ISSUE TITLE
metawrap (quant_bins) doesn't detect samples 

### ISSUE THREAD

**Issue by mars188** [bxlab/metaWRAP#388]
Hi, 

I am running the metawrap pipeline. I have 206 samples that I first concatenated them in 10 groups (A_case, A_control, B_case, B_control, C_case, C_control, D_case, D_control, E_case and E_control), and later into one big paired fastq file as shown below:

`cat A_case*1.fastq > A_case_1.fastq & cat A_case*2.fastq > A_case_2.fastq .....
cat A_control*1.fastq > A_control_1.fastq & cat B_control*2.fastq > B_control_2.fastq `

Then combined all:

`cat *1.fastq > ALL_READS_1.fastq and cat *2.fastq > ALL_READS_2.fastq`

Using these ALL_READS fastq files, I ran assembly, binning, bin refinement and abundance modules using metawrap pipeline. However, during the abundance module, it says "There were 1 samples detected" (I was expecting it to be 10 samples) and it generated abundance for only one sample. So, why metawrap is treating all the reads as one? even though I had 10 different groups?

Please help to solve this issue. 

Many thanks in advance!

**Comment by ursky** [comment]
Can you provide the full command and output when you run the quant_bins module?

**Comment by mars188** [comment]
Here is the full command:

`metawrap quant_bins -o analysis/ALL_READS_tp/abundance/ -t 64 -b analysis/ALL_READS_tp/bin_ref/metawrap_90_5_bins/ -a analysis/ALL_READS_tp/megahit/final_assembly.fasta clean_reads/ALL_READS_tp*fastq`

**Comment by mars188** [comment]
Ok I think, I may understand the issue. may be may be...

For the last part of the command, I should give reference to the individual samples and not the concatenated reads?
Should be `clean_reads/sampl*fastq` instead of `clean_reads/ALL_READS_tp*fastq`

Let me run this one and then will update you. Thanks

**Comment by ursky** [comment]
Correct!

**Comment by mars188** [comment]
Yes, it worked. Thanks for showing up, that made a difference :)
