### ISSUE TITLE
still lots of humans reads after running metaWRAP-Read_qc w/bmtagger

### ISSUE THREAD

**Issue by spencer411** [bxlab/metaWRAP#390]
Homo sapiens are my number one species when looking at my kraken output despite running metaWRAP-Read_qc w/bmtagger for soil sediment samples taken from the ocean. I have double checked the path to my bmtagger database and there are host_read fastq files created with sequences in them, so I am confused as to why all these human reads are still being identified/left in. Any inference as to what might be going on is appreicated.

**Comment by mars188** [comment]
I had the same issue with my gut microbiome samples. Please do write up here if you find a solution.

**Comment by spencer411** [comment]
Just an update here. I built a kraken database using only bacteria per the instructions on the kraken2 database build page which solved the problem for the purpose of the study I was working on. Nevertheless, this does not solve the problem of bmtagger failing to adequately remove human reads.
