### ISSUE TITLE
BLAST Database error: Error: Not a valid version 4 database. (metaWRAP)

### ISSUE THREAD

**Issue by kalonji08** [bxlab/metaWRAP#423]
Hello i ran the following code:
metawrap blobology -a /mnt/sdb/HC3_analysis/assembly_output/final_assembly.fasta -t 30 -o /mnt/sdb/HC3_analysis/blobology_s1 --bins /mnt/sdb/HC3_analysis/refinment_bin/metawrap_80_10_bins /mnt/sdb/HC3_analysis/HC3_Raws/HC3_R_1.fastq /mnt/sdb/HC3_analysis/HC3_Raws/HC3_R_2.fastq

and got this response:
------------------------------------------------------------------------------------------------------------------------
-----                                  1 forward and 1 reverse read files detected                                 -----
------------------------------------------------------------------------------------------------------------------------

########################################################################################################################
########################################################################################################################

Warning: /mnt/sdb/HC3_analysis/blobology_s1 already exists.

------------------------------------------------------------------------------------------------------------------------
-----                                   Running MEGABLAST on final_assembly.fasta                                  -----
------------------------------------------------------------------------------------------------------------------------

BLAST Database error: Error: Not a valid version 4 database.

************************************************************************************************************************
*****                Something went wrong with assigning taxonomy to contigs with megablast. Exiting               *****
************************************************************************************************************************

real    0m2.197s
user    0m0.078s
sys     0m0.291s
********************************************************************************************************************************************
I must also add that it was a bit of a strugle to download the NCBI_NT database
i have manged to merge : nt00 -nt.54

Any assistance will appreciated

**Comment by mrgambero** [comment]
No solution?

**Comment by kalonji08** [comment]
Nope, i will try it on a different workstation but i ended up using: MAGpy to classify my MAGs
https://academic.oup.com/bioinformatics/article/35/12/2150/5172363

**Comment by mrgambero** [comment]
I installed the new version of blast just by downloading it from the NCBI website and putting the executable in the bin folder of the conda environment. It worked but now I am facing a new problem.
Metawrap seems like a neverending stream of errors.

**Comment by mrgambero** [comment]
Something to do with ggplot2 in the  R script that crates the blob graphs. I have not had time to look at it yet.

**Comment by kalonji08** [comment]
@mrgambero Good luck hopefully it works!
