### ISSUE TITLE
choice of Taxator-Tk

### ISSUE THREAD

**Issue by jorondo1** [bxlab/metaWRAP#426]
Hi @ursky and collaborators,

This is not really an issue, but since I thought your answer might interest others I'm posting it here. Could you share your rationale behind choosing Taxator as a classifier? I am currently reviewing tools used in assembly pipelines (and getting very excited to use metaWRAP!) and I can't seem to find any argument for or against the use of Taxator-tk in comparison for example to GTDB-Tk when it comes to MAGs.

Since it really looks like every step of metaWRAP has been thoroughly thought-through, would you briefly share why you favour Taxator-Tk over other alternatives?

Best regards,
Jo

**Comment by ursky** [comment]
At the time, Taxator-Tk reported some of the lowest false-positive rates when identifying contigs, and thus was a "safe" choice. The way I use it in metawrap, the module produces very conservative classifications and doesn't classify beyond the class/order unless its very sure. This is usually ok for a first pass but not sufficient for a more in-depth look. 

Classify_bins is a safe first-pass thing to run, but to be frank there are much better modern ways of taxonomic classification of MAGs that focus on marker genes. I have not followed the field closely but I hear GTDB-Tk is good. I am least proud of this module and I don't honestly recommend you use it in 2022. Most other components still hold up very well (see https://www.biorxiv.org/content/10.1101/2021.07.12.451567v1.abstract).

**Comment by jorondo1** [comment]
Thanks a lot for the extra-quick reply, that's very helpful. Looking forward to running this !
________________________________
De : Gherman V. Uritskiy ***@***.***>
Envoyé : 7 mars 2022 17:13
À : bxlab/metaWRAP ***@***.***>
Cc : Jonathan Rondeau-Leclaire ***@***.***>; Author ***@***.***>
Objet : Re: [bxlab/metaWRAP] choice of Taxator-Tk (Issue #426)


At the time, Taxator-Tk reported some of the lowest false-positive rates when identifying contigs, and thus was a "safe" choice. The way I use it in metawrap, the module produces very conservative classifications and doesn't classify beyond the class/order unless its very sure. This is usually ok for a first pass but not sufficient for a more in-depth look.

Classify_bins is a safe first-pass thing to run, but to be frank there are much better modern ways of taxonomic classification of MAGs that focus on marker genes. I have not followed the field closely but I hear GTDB-Tk is good. I am least proud of this module and I don't honestly recommend you use it in 2022. Most other components still hold up very well (see https://www.biorxiv.org/content/10.1101/2021.07.12.451567v1.abstract<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.biorxiv.org%2Fcontent%2F10.1101%2F2021.07.12.451567v1.abstract&data=04%7C01%7Cronj2303%40usherbrooke.ca%7C5d9b732a8ef34d553dd008da0087bdf9%7C3a5a8744593545f99423b32c3a5de082%7C0%7C0%7C637822880248693354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XsV0zG6tLzxuS0Ozb5RY4HiUgBden6WblhMZalW3Lq0%3D&reserved=0>).

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbxlab%2FmetaWRAP%2Fissues%2F426%23issuecomment-1061191437&data=04%7C01%7Cronj2303%40usherbrooke.ca%7C5d9b732a8ef34d553dd008da0087bdf9%7C3a5a8744593545f99423b32c3a5de082%7C0%7C0%7C637822880248693354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kD02v4KWCyHvfvwJw9Qg71CzqChnvyMpS0dEkXXPnMM%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXLRUVCACGFACMIMVCBISALU6Z5RNANCNFSM5PYYAACA&data=04%7C01%7Cronj2303%40usherbrooke.ca%7C5d9b732a8ef34d553dd008da0087bdf9%7C3a5a8744593545f99423b32c3a5de082%7C0%7C0%7C637822880248693354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=60aaQN1dmFJSS%2FUIrHXPj6dWDKAeqEJKBQ6LRmqeEp0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cronj2303%40usherbrooke.ca%7C5d9b732a8ef34d553dd008da0087bdf9%7C3a5a8744593545f99423b32c3a5de082%7C0%7C0%7C637822880248693354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=adFUEqJRBCC1QyDG0UbK8xN5F8N0tndSHyZiQQOrT%2Bw%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cronj2303%40usherbrooke.ca%7C5d9b732a8ef34d553dd008da0087bdf9%7C3a5a8744593545f99423b32c3a5de082%7C0%7C0%7C637822880248849578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=saCCoNRuSHwmafIl3kaHPUpoAfbqfEdnbNxUXifsUt8%3D&reserved=0>.

**Comment by ursky** [comment]
No problem :)

**Comment by jorondo1** [comment]
We're probably gonna be playing around with the script, ex. use bowtie2 instead of bwa to take advantage of the multithreading capacity of the index builder. It makes me want to ask, what other components could be improved upon in your opinion? no need to dive into details, but if something comes to mind, I'd love to look into that.
