### ISSUE TITLE
Conflicts while installing dependancies

### ISSUE THREAD

**Issue by jonaskohh** [bxlab/metaWRAP#507]
Hello. I am trying to install metawrap and I have done the following: 

1. Installing miniconda2
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
bash Miniconda2-latest-Linux-x86_64.sh

2. Creating new metawrap environment for dependencies 
conda create -y -n metawrap-env python=2.7
source activate metawrap-env

conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
conda config --add channels ursky

I have tried "conda install -y -c ursky metawrap-mg" but there are always conflicts, so I have decided to install the dependencies one by one. I have found that "r-ggplot2" and "kraken2 (I had to use "conda install -c bioconda kraken2" as "conda install kraken=2.0" resulted in PackagesNotFoundError) have conflicts and therefore cannot be installed. 

Is there a way to solve this problem? Thank you!

**Comment by yqy6611** [comment]
Don't restrict python version and it will be fine. Majority of dependencies rely on python 3 now.

**Comment by jonaskohh** [comment]
Do I still use miniconda2 then?

**Comment by yqy6611** [comment]
Should be okay. I prefer miniconda 3
