### ISSUE TITLE
How do I improve the parameters of spades in "reassemble_bins"

### ISSUE THREAD

**Issue by YR020202** [bxlab/metaWRAP#508]
I found the spades used in the "reassemble_bins" command. I want to change some parameters of spades. For example, I want to set the value of k to 21,33,55,77,99,127, and change untrusted-contigs to trusted-contigs. May I ask how to change the above parameters? 

Thank you very much!

**Comment by yqy6611** [comment]
Just revise the script of reassemble_bins

**Comment by YR020202** [comment]
> Just revise the script of reassemble_bins

Thank you very much for your valuable advice. Could you please tell me the specific modification method? I'm not good at revising script.

**Comment by YR020202** [comment]
> Just revise the script of reassemble_bins
I found "reassemble_bins.sh" from ~/mambaforge-pypy3/envs/metawrap-new/bin/metawrap-modules/reassemble_bins.sh
The command for spades is as follows:

announcement "REASSEMBLING BINS WITH SPADES"
mkdir ${out}/reassemblies

assemble () {
	bin_name=${1%_*}
	if [[ -s ${out}/reassemblies/${bin_name}/scaffolds.fasta ]]; then
		comm "Looks like $bin_name was already re-assembled. Skipping..."
	else
		tmp_dir=${out}/reassemblies/${bin_name}.tmp
		mkdir $tmp_dir
		comm "NOW REASSEMBLING ${bin_name}"
		spades.py -t $2 -m $mem --tmp $tmp_dir --careful \
		--untrusted-contigs ${out}/original_bins/${bin_name%.*}.fa \
		-1 ${out}/reads_for_reassembly/${1%_*}_1.fastq \
		-2 ${out}/reads_for_reassembly/${1%_*}_2.fastq \
		-o ${out}/reassemblies/${bin_name}

Is this part to be modified? However, after I modified it, a "permission denied" error appeared in the operation.
Did I change it incorrectly? So how do you revise it?

**Comment by yqy6611** [comment]
'sudo nano' or 'sudo vi' is for this circumstance.
